/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progettoasta;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * Classe Frame Banditore
 *
 * @author Farhan
 */
public class FRMBanditore extends javax.swing.JFrame implements Observer {

    /*Attributi*/
    private MODBanditore mb;
    private ArrayList<MODAstante> listaAst;
    private DefaultListModel DLM;
    private final String imgPth = "/Images/";

    /*Costruttore*/
    /**
     * Creates new form Banditore
     */
    public FRMBanditore(MODBanditore modello) {
        toDoFirst(modello);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNotifiche = new javax.swing.JPanel();
        lblTempo = new javax.swing.JLabel();
        lblTotAstanti = new javax.swing.JLabel();
        panCentrale = new javax.swing.JPanel();
        panUtil = new javax.swing.JPanel();
        lblTitlePrezzo = new javax.swing.JLabel();
        lblPrezzo = new javax.swing.JLabel();
        lblTitleMgOff = new javax.swing.JLabel();
        lblMaggOff = new javax.swing.JLabel();
        lblTitlePrezzoAtt = new javax.swing.JLabel();
        lblPrezzoAtt = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        panTitle = new javax.swing.JPanel();
        lblNomeOggAsta = new javax.swing.JLabel();
        lblTitleProprietario = new javax.swing.JLabel();
        lblProprietario = new javax.swing.JLabel();
        panListaAstanti = new javax.swing.JPanel();
        scrPanLista = new javax.swing.JScrollPane();
        listElencoNomi = new javax.swing.JList();
        lblTitleAstanti = new javax.swing.JLabel();
        panStrumenti = new javax.swing.JPanel();
        lblTitleSetTime = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        lblTitleMin = new javax.swing.JLabel();
        lblTitleSec = new javax.swing.JLabel();
        txtSec = new javax.swing.JTextField();
        btnAvvioAsta = new javax.swing.JButton();
        btnConfermWiner = new javax.swing.JButton();
        btnStopAsta = new javax.swing.JButton();
        lblMessaggi = new javax.swing.JLabel();
        mBar = new javax.swing.JMenuBar();
        menuTitle = new javax.swing.JMenu();
        menuRefresh = new javax.swing.JMenuItem();
        nxtArt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banditore");

        panNotifiche.setBackground(new java.awt.Color(204, 204, 204));

        lblTempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTempo.setText("00:00");

        lblTotAstanti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotAstanti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotAstanti.setText("0 ast.");

        javax.swing.GroupLayout panNotificheLayout = new javax.swing.GroupLayout(panNotifiche);
        panNotifiche.setLayout(panNotificheLayout);
        panNotificheLayout.setHorizontalGroup(
            panNotificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNotificheLayout.createSequentialGroup()
                .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotAstanti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panNotificheLayout.setVerticalGroup(
            panNotificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNotificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotAstanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panCentrale.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePrezzo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePrezzo.setText("Prezzo di partenza: ");

        lblPrezzo.setBackground(new java.awt.Color(204, 255, 204));
        lblPrezzo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrezzo.setText("0 €");

        lblTitleMgOff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitleMgOff.setText("Maggior offerente: ");

        lblMaggOff.setBackground(new java.awt.Color(204, 255, 204));
        lblMaggOff.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMaggOff.setText("Nessuno");

        lblTitlePrezzoAtt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePrezzoAtt.setText("Prezzo attuale: ");

        lblPrezzoAtt.setBackground(new java.awt.Color(204, 255, 204));
        lblPrezzoAtt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrezzoAtt.setText("0 €");

        javax.swing.GroupLayout panUtilLayout = new javax.swing.GroupLayout(panUtil);
        panUtil.setLayout(panUtilLayout);
        panUtilLayout.setHorizontalGroup(
            panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUtilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTitleMgOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrezzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitlePrezzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaggOff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrezzoAtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitlePrezzoAtt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panUtilLayout.setVerticalGroup(
            panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUtilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitlePrezzo)
                    .addComponent(lblTitlePrezzoAtt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezzo)
                    .addComponent(lblPrezzoAtt))
                .addGap(18, 18, 18)
                .addComponent(lblTitleMgOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaggOff)
                .addGap(35, 35, 35))
        );

        lblFoto.setBackground(new java.awt.Color(204, 255, 204));
        lblFoto.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblNomeOggAsta.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblNomeOggAsta.setText("Titolo");

        lblTitleProprietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitleProprietario.setText("Proprietario: ");

        lblProprietario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProprietario.setText("Nome");
        lblProprietario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panTitleLayout = new javax.swing.GroupLayout(panTitle);
        panTitle.setLayout(panTitleLayout);
        panTitleLayout.setHorizontalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleProprietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblNomeOggAsta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panTitleLayout.setVerticalGroup(
            panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTitleLayout.createSequentialGroup()
                .addComponent(lblNomeOggAsta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTitleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitleProprietario))
                    .addComponent(lblProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        scrPanLista.setViewportView(listElencoNomi);

        lblTitleAstanti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitleAstanti.setText("Partecipanti all' asta: ");

        javax.swing.GroupLayout panListaAstantiLayout = new javax.swing.GroupLayout(panListaAstanti);
        panListaAstanti.setLayout(panListaAstantiLayout);
        panListaAstantiLayout.setHorizontalGroup(
            panListaAstantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaAstantiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panListaAstantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPanLista)
                    .addGroup(panListaAstantiLayout.createSequentialGroup()
                        .addComponent(lblTitleAstanti)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panListaAstantiLayout.setVerticalGroup(
            panListaAstantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panListaAstantiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleAstanti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPanLista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTitleSetTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitleSetTime.setText("Imposta tempo: ");

        txtMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMin.setText("00");

        lblTitleMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMin.setText("min.");

        lblTitleSec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSec.setText("sec.");

        txtSec.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSec.setText("00");

        btnAvvioAsta.setText("Avvia asta");
        btnAvvioAsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvvioAstaActionPerformed(evt);
            }
        });

        btnConfermWiner.setText("Conferma vincitore");
        btnConfermWiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermWinerActionPerformed(evt);
            }
        });

        btnStopAsta.setText("Ferma asta");
        btnStopAsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopAstaActionPerformed(evt);
            }
        });

        lblMessaggi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMessaggi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessaggi.setText("-");

        javax.swing.GroupLayout panStrumentiLayout = new javax.swing.GroupLayout(panStrumenti);
        panStrumenti.setLayout(panStrumentiLayout);
        panStrumentiLayout.setHorizontalGroup(
            panStrumentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStrumentiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panStrumentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panStrumentiLayout.createSequentialGroup()
                        .addComponent(lblTitleSetTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitleSec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSec, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfermWiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panStrumentiLayout.createSequentialGroup()
                        .addComponent(btnAvvioAsta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStopAsta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMessaggi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panStrumentiLayout.setVerticalGroup(
            panStrumentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStrumentiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panStrumentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleSetTime)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleMin)
                    .addComponent(txtSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitleSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panStrumentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvvioAsta)
                    .addComponent(btnStopAsta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfermWiner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblMessaggi)
                .addContainerGap())
        );

        javax.swing.GroupLayout panCentraleLayout = new javax.swing.GroupLayout(panCentrale);
        panCentrale.setLayout(panCentraleLayout);
        panCentraleLayout.setHorizontalGroup(
            panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentraleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panUtil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panListaAstanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panStrumenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCentraleLayout.setVerticalGroup(
            panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentraleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panCentraleLayout.createSequentialGroup()
                        .addComponent(panTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCentraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panListaAstanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panStrumenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuTitle.setText("Asta");

        menuRefresh.setText("Aggiorna");
        menuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRefreshActionPerformed(evt);
            }
        });
        menuTitle.add(menuRefresh);

        nxtArt.setText("Prosimo articolo");
        nxtArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtArtActionPerformed(evt);
            }
        });
        menuTitle.add(nxtArt);

        mBar.add(menuTitle);

        setJMenuBar(mBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panNotifiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCentrale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panNotifiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCentrale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo che cattura l'evento del button che avvia il timer
     *
     * @param evt(ActionEvent)
     */
    private void btnAvvioAstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvvioAstaActionPerformed
        try {
            int MIN = Integer.parseInt(txtMin.getText());
            int SEC = Integer.parseInt(txtSec.getText());
            mb.startCDT(MIN, SEC);
        } catch (Exception e) {
            lblMessaggi.setText("Tempo Non Valido!");
        }
    }//GEN-LAST:event_btnAvvioAstaActionPerformed
    /**
     * Metodo che cattura l'evento del button che ferma il timer
     *
     * @param evt (ActionEvent)
     */
    private void btnStopAstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopAstaActionPerformed
        try {
            mb.stopCDT();
            lblMessaggi.setText("Timer fermato con successo!");
        } catch (Exception e) {
            lblMessaggi.setText("Qualcosa e' andato storto :-(");
        }
    }//GEN-LAST:event_btnStopAstaActionPerformed
    /**
     * Metodo che cattura l'evento del button che conferma il vincitore
     *
     * @param evt (ActionEvent)
     */
    private void btnConfermWinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermWinerActionPerformed
        if (mb.isCntDwnFinished()) {
            mb.confermaVincitore();
            try {
                mb.aggiornaAsta();
            } catch (SQLException ex) {
                lblMessaggi.setText("Qualcosa e' andato storto :-(");
                Logger.getLogger(FRMBanditore.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblMessaggi.setText("Confermato con successo!");
        } else {
            lblMessaggi.setText("Impossibile confermare vincitore!");
        }
    }//GEN-LAST:event_btnConfermWinerActionPerformed
    /**
     * Metodo che cattura l'evrnto del button che carica il prossimo articolo
     *
     * @param evt (ActionEvent)
     */
    private void nxtArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtArtActionPerformed
        if (mb.isCntDwnFinished()) {
            try {
                mb.nxtArt();
            } catch (Exception e) {
                lblMessaggi.setText("Sono finiti gli articoli in asta!");
            }
        } else {
            lblMessaggi.setText("Impossibile cambiare articolo!");
        }
    }//GEN-LAST:event_nxtArtActionPerformed
    /**
     * Metodo che cattra l'evento che aggiorna gli articoli in asta
     *
     * @param evt (ActionEvent)
     */
    private void menuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRefreshActionPerformed
        try {
            mb.aggiornaAsta();
        } catch (SQLException ex) {
            lblMessaggi.setText("Qualcosa e' andato storto :-(");
            Logger.getLogger(FRMBanditore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvioAsta;
    private javax.swing.JButton btnConfermWiner;
    private javax.swing.JButton btnStopAsta;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblMaggOff;
    private javax.swing.JLabel lblMessaggi;
    private javax.swing.JLabel lblNomeOggAsta;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JLabel lblPrezzoAtt;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblTitleAstanti;
    private javax.swing.JLabel lblTitleMgOff;
    private javax.swing.JLabel lblTitleMin;
    private javax.swing.JLabel lblTitlePrezzo;
    private javax.swing.JLabel lblTitlePrezzoAtt;
    private javax.swing.JLabel lblTitleProprietario;
    private javax.swing.JLabel lblTitleSec;
    private javax.swing.JLabel lblTitleSetTime;
    private javax.swing.JLabel lblTotAstanti;
    private javax.swing.JList listElencoNomi;
    private javax.swing.JMenuBar mBar;
    private javax.swing.JMenuItem menuRefresh;
    private javax.swing.JMenu menuTitle;
    private javax.swing.JMenuItem nxtArt;
    private javax.swing.JPanel panCentrale;
    private javax.swing.JPanel panListaAstanti;
    private javax.swing.JPanel panNotifiche;
    private javax.swing.JPanel panStrumenti;
    private javax.swing.JPanel panTitle;
    private javax.swing.JPanel panUtil;
    private javax.swing.JScrollPane scrPanLista;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtSec;
    // End of variables declaration//GEN-END:variables

    private void toDoFirst(MODBanditore modello) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMBanditore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMBanditore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMBanditore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMBanditore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(true);
            }
        });
        this.mb = modello;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof MODBanditore) {
            if (arg instanceof ArrayList) {
                setListAstanti((ArrayList<MODAstante>) arg);
            } else if (arg instanceof ArticoloAsta) {
                setArticolo((ArticoloAsta) arg);
            }
        } else if (o instanceof CntDwnTimer) {
            setTimer(arg);
        }
    }

    /**
     * Metodo per mostrare tutti gli astanti
     *
     * @param arg (ArrayList)
     */
    private void setListAstanti(ArrayList<MODAstante> arg) {
        listaAst = (ArrayList<MODAstante>) arg;
        DLM = new DefaultListModel();
        for (Object x : listaAst) {
            DLM.addElement(x.toString());
        }
        listElencoNomi.setModel(DLM);
        lblMaggOff.setText(listaAst.get(0).getNome());
        lblPrezzoAtt.setText("" + listaAst.get(0).getOfferta());
        lblTotAstanti.setText(listaAst.size() + " ast.");
    }

    /**
     * Metodo che definisce il layout della schermata quando sa l'articolo
     * all'asta
     *
     * @param art (ArticoloAsta)
     */
    private void setArticolo(ArticoloAsta art) {
        lblNomeOggAsta.setText(art.getName());
        lblProprietario.setText(art.getOwner());
        lblPrezzo.setText(art.getPrezzo() + " €");
        lblPrezzoAtt.setText("0 €");
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource(imgPth + art.getFotoName())));
    }

    /**
     * Metodo che definisce il layout della schermata quando sa il tempo
     *
     * @param timer (Object)
     */
    private void setTimer(Object timer) {
        lblTitleMgOff.setText(mb.isCntDwnFinished() ? "Ha Vinto: " : "Maggior offerente: ");
        int[] temp = (int[]) timer;
        String MIN = (temp[0] < 10 ? "0" + temp[0] : "" + temp[0]);
        String SEC = (temp[1] < 10 ? "0" + temp[1] : "" + temp[1]);
        lblTempo.setForeground(temp[0] < 1 ? Color.RED : Color.BLACK);
        lblTempo.setText(MIN + ":" + SEC);
    }
}
