PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS ACCESSO;
DROP TABLE IF EXISTS PERSONA;


CREATE TABLE PERSONA(
    idPersona INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(40)
);

CREATE TABLE ACCESSO(
    idAccesso INTEGER PRIMARY KEY AUTOINCREMENT,
    dataOra VARCHAR(100),
    idPersona INTEGER,

    FOREIGN KEY(idPersona) REFERENCES PERSONA(idPersona)
);

INSERT INTO PERSONA(username) VALUES('mario.rossi');
INSERT INTO ACCESSO(dataOra,idPersona) VALUES('30/04/2018 09:22', 1);